### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by Oniurain** [Danistc/react-allergens#1]
Hi, great icons!
It's look like the new build (0.2.0) is not the last one, you need to generate (and publish).
I have the issue with mustard icon and I can't change the wrapperStyle, but if I checkout your package and build it locally all it's fine.

Thanks for you work

**Comment by dsanchez07** [comment]
Hi @Oniurain !!

I'll have it fixed this afternoon, sorry for the late answer!

**Comment by Oniurain** [comment]
Thank you, I close the issue (and my fork :) )

**Comment by dsanchez07** [comment]
Version updated @Oniurain , sorry for the delay again and glad that you liked it! :)
